name: CI
on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - 'docs/*'
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - git-brws.1
      - git-brws.1.ronn
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Install Rust via Rustup
        run: |
          rustup update stable
          rustup default stable
          rustc -V
          cargo -V
      - uses: actions/checkout@v2
      - name: Set Git user for running Git commands in unit tests
        run: |
          git config --global user.email "users@noreply.github.com"
          git config --global user.name "github-action"
      - name: Fetch Git history for unit tests
        run: |
          git fetch --prune --unshallow
          git fetch origin master:master
      - name: Show warning
        if: matrix.os != 'ubuntu-latest'
        run: echo "::warning file=src/test/helper.rs::Skipping tests for GitHub API on this platform due to rate limit. git-brws uses GitHub search API but it has special rate limit 30/min and running jobs parallelly hits the limit"
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo test --verbose
